# Optimizes the landing-reel clips for web. For each clip it produces two
# candidates and keeps the SMALLER, so a clip is never made bigger:
#   A) re-encode: H.264 CRF 26, fit within 1080p, audio stripped, +faststart
#   B) remux:     copy video as-is, audio stripped, +faststart (no quality loss)
# A wins on high-bitrate / high-res sources; B wins on already-efficient ones.
# Reads from videoclips/reel/, writes results to public/clips/ as NN.mp4 and
# regenerates src/data/clips.ts. This is the heavier alternative to
# sync-clips.ps1 (which just copies) and requires ffmpeg.
# Requires ffmpeg (pass -Ffmpeg <path> or rely on the portable default).

param([string]$Ffmpeg = "$env:LOCALAPPDATA\ffmpeg\ffmpeg-master-latest-win64-gpl\bin\ffmpeg.exe")

$root = Split-Path $PSScriptRoot -Parent
$src  = Join-Path $root 'videoclips\reel'
$dest = Join-Path $root 'public\clips'

if (-not (Test-Path -LiteralPath $Ffmpeg)) { Write-Error "ffmpeg not found at $Ffmpeg"; exit 1 }
if (Test-Path -LiteralPath $dest) { Remove-Item -LiteralPath $dest -Recurse -Force }
New-Item -ItemType Directory -Force $dest | Out-Null

$files = Get-ChildItem -LiteralPath $src -File |
  Where-Object { $_.Extension -imatch '\.(mp4|m4v|mov|webm)$' } |
  Sort-Object Name

# fit within 1080p, only downscaling, keeping aspect + even dimensions
$vf = "scale='min(1920,iw)':'min(1080,ih)':force_original_aspect_ratio=decrease:force_divisible_by=2"

$lines = @()
$i = 1
$totalIn = 0.0; $totalOut = 0.0
foreach ($f in $files) {
  $name = '{0:d2}.mp4' -f $i
  $out  = Join-Path $dest $name
  $tmpA = Join-Path $dest "_A_$name"
  $tmpB = Join-Path $dest "_B_$name"

  # A — re-encode
  & $Ffmpeg -y -hide_banner -loglevel error -i $f.FullName `
    -an -c:v libx264 -profile:v high -pix_fmt yuv420p -crf 26 -preset medium `
    -vf $vf -movflags +faststart $tmpA
  # B — lossless remux (strip audio + faststart only)
  & $Ffmpeg -y -hide_banner -loglevel error -i $f.FullName `
    -an -c:v copy -movflags +faststart $tmpB

  $aOK = Test-Path -LiteralPath $tmpA
  $bOK = Test-Path -LiteralPath $tmpB
  $aSz = if ($aOK) { (Get-Item -LiteralPath $tmpA).Length } else { [long]::MaxValue }
  $bSz = if ($bOK) { (Get-Item -LiteralPath $tmpB).Length } else { [long]::MaxValue }

  if (-not $aOK -and -not $bOK) { Write-Output "FAILED: $($f.Name)"; continue }

  if ($aSz -le $bSz) { Move-Item -LiteralPath $tmpA -Destination $out -Force; if ($bOK) { Remove-Item -LiteralPath $tmpB -Force }; $pick = 're-encode' }
  else               { Move-Item -LiteralPath $tmpB -Destination $out -Force; if ($aOK) { Remove-Item -LiteralPath $tmpA -Force }; $pick = 'remux' }

  $inMB  = [math]::Round($f.Length / 1MB, 1)
  $outMB = [math]::Round((Get-Item -LiteralPath $out).Length / 1MB, 1)
  $totalIn += $inMB; $totalOut += $outMB
  Write-Output ("{0,2}  {1,7:N1} -> {2,7:N1} MB  [{3,-9}]  {4}" -f $i, $inMB, $outMB, $pick, $f.Name)
  $lines += "  '/clips/$name',"
  $i++
}

$ts = "/* AUTO-GENERATED by scripts/optimize-clips.ps1 - do not edit by hand.`n" +
      "   The landing reel shuffles and plays these clips (public/clips/). */`n" +
      "export const heroClips: string[] = [`n" + ($lines -join "`n") + "`n];`n"
[System.IO.File]::WriteAllText(
  (Join-Path $root 'src\data\clips.ts'),
  $ts,
  (New-Object System.Text.UTF8Encoding($false)))

Write-Output ("---`nDone: {0} clips, {1:N0} MB -> {2:N0} MB" -f ($i - 1), $totalIn, $totalOut)
