# Syncs the landing-reel clips.
#  - copies EVERY video in videoclips/ into public/clips/ as NN.mp4
#    (.m4v is the same MP4 container, so a .mp4 extension is safe + plays
#     reliably across browsers)
#  - removes the old public/media/clips/ folder
#  - regenerates src/data/clips.ts (the shuffle list the reel reads)
# Re-run after adding/removing files in videoclips/.

$root     = Split-Path $PSScriptRoot -Parent
$src      = Join-Path $root 'videoclips'
$dest     = Join-Path $root 'public\clips'
$oldClips = Join-Path $root 'public\media\clips'

# fresh public/clips
if (Test-Path -LiteralPath $dest) { Remove-Item -LiteralPath $dest -Recurse -Force }
New-Item -ItemType Directory -Force $dest | Out-Null

# every video file, sorted by name → 01.mp4, 02.mp4, ...
$files = Get-ChildItem -LiteralPath $src -File |
  Where-Object { $_.Extension -imatch '\.(mp4|m4v|mov|webm)$' } |
  Sort-Object Name
$lines = @()
$i = 1
foreach ($f in $files) {
  $name = '{0:d2}.mp4' -f $i
  Copy-Item -LiteralPath $f.FullName -Destination (Join-Path $dest $name) -Force
  $lines += "  '/clips/$name',"
  $i++
}

# erase the old clips
if (Test-Path -LiteralPath $oldClips) { Remove-Item -LiteralPath $oldClips -Recurse -Force }

# regenerate src/data/clips.ts (no BOM, so esbuild is happy)
$ts = "/* AUTO-GENERATED by scripts/sync-clips.ps1 - do not edit by hand.`n" +
      "   The landing reel shuffles and plays these clips (public/clips/).`n" +
      "   Re-run the script after adding/removing files in videoclips/. */`n" +
      "export const heroClips: string[] = [`n" +
      ($lines -join "`n") + "`n];`n"
[System.IO.File]::WriteAllText(
  (Join-Path $root 'src\data\clips.ts'),
  $ts,
  (New-Object System.Text.UTF8Encoding($false)))

Write-Output "Synced $($files.Count) clips into public/clips/ and wrote src/data/clips.ts"
