# Syncs the landing-reel clips.
#  - copies EVERY video in videoclips/reel/ into public/clips/ as NN.mp4
#    (.m4v is the same MP4 container, so a .mp4 extension is safe + plays
#     reliably across browsers)
#  - removes the old public/media/clips/ folder
#  - regenerates src/data/clips.ts (the shuffle list the reel reads)
#
# WHERE TO WORK: put ONLY the clips you want in the homepage reel into
# videoclips/reel/. Other raw masters live in videoclips/_archive/ and are
# ignored by the reel. Re-run this script after adding/removing files in
# videoclips/reel/, then commit public/clips/ + src/data/clips.ts.

$root     = Split-Path $PSScriptRoot -Parent
$src      = Join-Path $root 'videoclips\reel'
$dest     = Join-Path $root 'public\clips'
$oldClips = Join-Path $root 'public\media\clips'

# fresh public/clips. NOTE: we clear the generated NN.mp4 files one by one
# rather than removing the folder itself — Dropbox often holds a lock on the
# directory handle, which makes `Remove-Item -Recurse` on the folder fail.
New-Item -ItemType Directory -Force $dest | Out-Null
Get-ChildItem -LiteralPath $dest -File -ErrorAction SilentlyContinue |
  Where-Object { $_.Name -match '^\d{2}\.mp4$' } |
  ForEach-Object { try { Remove-Item -LiteralPath $_.FullName -Force } catch {} }

# every video file, sorted by name → 01.mp4, 02.mp4, ...
$files = Get-ChildItem -LiteralPath $src -File |
  Where-Object { $_.Extension -imatch '\.(mp4|m4v|mov|webm)$' } |
  Sort-Object Name
$lines = @()
$i = 1
foreach ($f in $files) {
  $name = '{0:d2}.mp4' -f $i
  Copy-Item -LiteralPath $f.FullName -Destination (Join-Path $dest $name) -Force
  $lines += "  '/clips/$name',"
  $i++
}

# erase the old clips
if (Test-Path -LiteralPath $oldClips) { Remove-Item -LiteralPath $oldClips -Recurse -Force }

# regenerate src/data/clips.ts (no BOM, so esbuild is happy)
$ts = "/* AUTO-GENERATED by scripts/sync-clips.ps1 - do not edit by hand.`n" +
      "   The landing reel shuffles and plays these clips (public/clips/).`n" +
      "   Re-run the script after adding/removing files in videoclips/reel/. */`n" +
      "export const heroClips: string[] = [`n" +
      ($lines -join "`n") + "`n];`n"
[System.IO.File]::WriteAllText(
  (Join-Path $root 'src\data\clips.ts'),
  $ts,
  (New-Object System.Text.UTF8Encoding($false)))

Write-Output "Synced $($files.Count) clips into public/clips/ and wrote src/data/clips.ts"
